Repository hwbit/PrepPal, pull requests merged in 2024-02, with the labels that each got.

#67 Explore/Homepage
  preppal-be/models/recipe.ts
  preppal-be/routes/recipeApi.ts
  preppal-fe/src/components/RecipeCard/RecipeCard.css
  preppal-fe/src/components/RecipeCard/RecipeCard.tsx
  preppal-fe/src/pages/home.tsx
  preppal-fe/src/styles/global.css
Labels: Enhancement

#83 Connect db with create recipe page
  preppal-fe/package-lock.json
  preppal-fe/package.json
  preppal-fe/src/__tests__/pages/new-recipes.test.tsx
  preppal-fe/src/pages/new-recipe.tsx
Labels: Creating Recipes Epic, Priority: High, Developer Task

#114 MongoDB schema for reviews, comments, rating
  preppal-be/models/comments.ts
Labels: Commenting/Reviews/Rating Epic, Priority: High, Developer Task
